language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main